language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main